language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main